language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main